language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main